language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main